name: Terraform Selective Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  selective-deploy:
    name: Apply Changed Terraform Module
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Detect Changed Directory
        id: detect
        run: |
          changed_dir=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | cut -d/ -f1 | sort -u | head -n1)
          echo "Changed directory: $changed_dir"
          echo "dir=$changed_dir" >> $GITHUB_OUTPUT

      - name: Terraform Init
        working-directory: ./${{ steps.detect.outputs.dir }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ./${{ steps.detect.outputs.dir }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./${{ steps.detect.outputs.dir }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./${{ steps.detect.outputs.dir }}
        run: terraform apply -auto-approve
