name: Terraform Selective Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Selective Terraform Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Changed Directory
        id: detect
        run: |
          changed_dirs=$(git diff ${{ github.event.before }} ${{ github.sha }} --name-only | awk -F/ '{print $1}' | sort -u | uniq)
          echo "Changed directories: $changed_dirs"
          echo "changed=$changed_dirs" >> $GITHUB_OUTPUT

      - name: Terraform EC2 Apply & Destroy
        if: contains(steps.detect.outputs.changed, 'ec2')
        working-directory: ./ec2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
          terraform destroy -auto-approve

      - name: Terraform S3 Apply & Destroy
        if: contains(steps.detect.outputs.changed, 's3')
        working-directory: ./s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
          terraform destroy -auto-approve
