name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # ✅ allows manual trigger from GitHub UI

jobs:
  ec2:
    name: EC2 Terraform Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ec2  # ✅ Use the ec2 directory

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  s3:
    name: S3 Terraform Job
    runs-on: ubuntu-latest
    needs: ec2  # ✅ Wait for ec2 job to succeed
    defaults:
      run:
        working-directory: ./s3  # ✅ Use the s3 directory

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
